# Generated by Django 3.2.25 on 2024-12-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_network_automation', '0004_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('mikrotik', 'Mikrotik'), ('cisco', 'Cisco')], max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
