# Generated by Django 3.2.25 on 2024-12-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_network_automation', '0005_auto_20241218_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorIP',
        ),
    ]
