# Generated by Django 3.2.25 on 2024-12-18 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_network_automation', '0006_delete_vendorip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='ssh_port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_network_automation.vendor'),
        ),
    ]
