# Generated by Django 3.2.25 on 2024-12-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_network_automation', '0007_auto_20241218_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('mikrotik', 'Mikrotik'), ('cisco', 'Cisco')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
