# Generated by Django 3.2.25 on 2024-12-24 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_network_automation', '0010_auto_20241224_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
